#######################################
# All settings are documented at https://kafka.apache.org/43/configuration/broker-configs/
#######################################

#######################################
# Broker setup
#######################################
# The roles this process performs. broker,controller means a combined broker/controller KRaft node.
process.roles=broker,controller

# The node id associated with this instance's roles
node.id=1

# A comma-separated list of the names of the listeners used by the controller.
controller.listener.names=CONTROLLER

# List of controller endpoints used connect to the controller cluster
controller.quorum.bootstrap.servers=localhost:9093

# Replication factor for the internal __consumer_offsets topic. 1 for a single-broker cluster
offsets.topic.replication.factor=1

# Disable the background thread that checks the distribution of partition leaders at regular intervals. Not needed for a single broker
auto.leader.rebalance.enable=false

# The largest message size allowed by the broker. We set this to 65MB
message.max.bytes=68157440

#######################################
# Network configuration
#######################################
# Listener name, hostname and port advertised to clients. INTERNAL is for to cloud VMs and EXTERNAL is for laptops
advertised.listeners=INTERNAL://10.67.22.90:19092,EXTERNAL://localhost:9092

# The address the socket server listens on
listeners=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

# Maps listener names to security protocols.
listener.security.protocol.map=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

# Listener used for communication between brokers
inter.broker.listener.name=INTERNAL

# The maximum size of a request that the socket will accept: 65MB
socket.request.max.bytes=68157440

# TCP receive buffer size used by broker sockets. 65MB
socket.receive.buffer.bytes=68157440

# TCP send buffer size used by broker sockets. 1MB
socket.send.buffer.bytes=1048576

#######################################
# Log storage / retention configuration
#######################################
# A comma separated list of directories under which to store log files. /tmp is mounted as tmpfs
log.dirs=/tmp/kraft-combined-logs

# The maximum time after which a log segment is closed. Closed segments are eligible for deletion according to log.retention policies
log.roll.ms=1000

# The maximum size of a log segment file. When this size is reached a new log segment will be created. We set this to 65MB
log.segment.bytes=68157440

# Delete log segments older than this retention period. Applies to closed segments
log.retention.minutes=3

# A size-based retention policy for logs. Functions independently of log.retention.hours. We set this to the size of 6 files (192MB)
log.retention.bytes=201326592

# The frequency that the log cleaner checks whether any log is eligible for deletion
log.retention.check.interval.ms=10000

# The amount of time to wait before deleting a segment scheduled for deletion
log.segment.delete.delay.ms=1000